directory = "_maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1/"

[rooms.commswilding]
modules = ["commswilding_1.dmm", "commswilding_2.dmm", "commswilding_3.dmm"]

[rooms.mistake]
modules = ["mistake_unlikely.dmm", "mistake_feasible.dmm", "mistake_inevitable.dmm"]

[rooms.engineering]
modules = ["engineering_supermatter","engineering_turbine","engineering_may_god_be_with_you"]

[rooms.dormitory]
modules = ["dormitory_engineer","dormitory_nerd"]
